### ISSUE TITLE
lagg spike load chunk

### ISSUE THREAD

**Issue by malsem** [crashtheparty/EnchantmentSolution#29]
There was a lagg spike caused by Enchantment Solution. It is because Enchantment Solution trying to fill loot chests with treasure maps on chunks load. Is there any way to fix it ?

Here's some thread dump from console:
https://pastebin.com/z6tfnzti

Here's the timings and the lagg spiked:
https://timings.aikar.co/?id=19fcf37df6534eeba71dd0154bcc5e45

What should i do to fix this issues? Thank you :)

**Comment by crashtheparty** [comment]
Does this happen often, or just once?

**Comment by malsem** [comment]
It happens when someone is exploring the map

**Comment by crashtheparty** [comment]
1. The event in the stack trace from Enchantment Solution that caused this was onPlayerInteract, not on generating chunks. Someone clicked on the chest to trigger it.
2. There are absolutely no loops in that section of code in Enchantment Solution. If there is an infinite loop being triggered, it is not the fault of Enchantment Solution from what I can see.
3. With how 1.14 is optimized, I wouldn’t be surprised if this was an issue of 1.14 loading chunks too slowly and causing massive lag when things happen in those newly generated chunks.
4. The two stack traces you sent, one at 10 seconds of slow time and one at 15 seconds, indicates that the function hasn’t necessarily stopped in one place but is going slowly through the methods necessary to generate the enchantments.

From this, I don’t think it’s an issue with Enchantment Solution, but if you can reproduce the issue using the following steps, I can try to take another look.

1. Go to a newly generated chunk that has a loot chest (sunken treasure or otherwise) in it
2. Wait until your render distance has been fully loaded around you.
3. Open the chest.

Prevent other players from loading new chunks while doing this. If there are no issues sent to the console, this is just a 1.14 optimization issue. If there are, continue to send the errors here, as well as the debug.yml file generated from /esdebug
