### ISSUE TITLE
Polish transcription

### ISSUE THREAD

**Issue by nicielpl** [crashtheparty/EnchantmentSolution#78]
When I try to polish the English plugin, it crashes everything back to English, I hope that this transcription is because I urgently need it :)

**Comment by crashtheparty** [comment]
This sounds like a bug. Please use the Bug Report framework so I can get more information about what's happening so I can help you.

**Comment by nicielpl** [comment]
what exactly to do because I do not know and for the first time something also report what to take exactly

**Comment by crashtheparty** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**Debug.yml**
Please send the debug.yml file generated using /esdebug to the bug report. You may use the file uploader on GitHub or a service like [pastebin](https://www.pastebin.com) and send the URL in this area. *Any issues that do not have the debug.yml information will be marked as closed immediately*.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by nicielpl** [comment]
such a question in this topic or create a new one?

**Comment by crashtheparty** [comment]
Do it in a new one.
